Vga bram
Boulderboys/ClimbingGameSoftware pull request #1
Opened 2024-12-12 14:19 UTC by MayorBosranger

## Beschrijving
Korte beschrijving van wat er is veranderd.

## Tests
- [ ] Aanpassingen zijn getest door ontwikkelaar
- [ ] Aanpassingen zijn getest door reviewer

## Checklist
- [ ] De code compileert/synthetiseert zonder fouten
- [ ] De code volgt de afgesproken conventies
- [ ] FO is bijgewerkt (of n.v.t.)
- [ ] TO is bijgewerkt (of n.v.t.)
- [ ] Geen TODO's
- [ ] Geen ongebruikte code

## Opmerkingen

2024-12-12 14:47 UTC, Wrymouth requested changes

2024-12-12 14:47 UTC, Wrymouth commented on .gitignore
Onnodig, deze soorten bestanden komen toch niet in de git terecht (hopelijk!)

2024-12-12 14:47 UTC, Wrymouth commented on src/BRAM_controller.cpp
> +bool Hand_Closed[2] = {FALSE, FALSE};
Gebruik structs 👀

2024-12-12 14:47 UTC, Wrymouth commented on src/BRAM_controller.cpp
> +bool Hand_Closed[2] = {FALSE, FALSE};
```
struct Hand { 
     bool closed;
     bool available;
}
```

2024-12-12 15:14 UTC, Wrymouth requested changes

2024-12-12 15:14 UTC, Wrymouth commented on src/BRAM_controller.cpp
> +struct Hand_speler{
PascalCase

2024-12-12 15:14 UTC, Wrymouth commented on src/BRAM_controller.cpp
>  void set_Hand_Closed(bool left, bool right){
snake_case is alleen kleine letters

2024-12-12 15:14 UTC, Wrymouth commented on src/BRAM_controller.cpp
> +struct Hand_speler{
HandSpeler

2024-12-12 15:14 UTC, Wrymouth commented on src/BRAM_controller.cpp
>  void set_Hand_Closed(bool left, bool right){
set_hand_closed

2024-12-12 15:14 UTC, Wrymouth commented on src/BRAM_controller.cpp
> +Hand_speler Hands[2] {{TRUE, FALSE, 0,0}, {TRUE, FALSE, 0, 0}};
hands

2024-12-13 11:13 UTC, WouterHielkema approved these changes
Joepie!! Goed bezig

2024-12-13 11:17 UTC, Wrymouth approved these changes

2024-12-13 11:17 UTC, merged